spring:
  datasource:
    url: jdbc:mysql://${MYSQLDB_HOST:49.234.129.151}:${MYSQLDB_DOCKER_PORT:3306}/${MYSQLDB_DATABASE:adminMysql}
    username: ${MYSQLDB_USER:root}
    password: ${MYSQLDB_ROOT_PASSWORD:123456}

  data:
    redis:
      host: ${REDIS_HOST:49.234.129.151}
      port: ${REDIS_DOCKER_PORT:6379}



