spring:
  datasource:
    url: jdbc:mysql://${MYSQLDB_HOST:49.234.129.151}:${MYSQLDB_DOCKER_PORT:3306}/${MYSQLDB_DATABASE:adminMysql}
    username: ${MYSQLDB_USER:root}
    password: ${MYSQLDB_ROOT_PASSWORD:123456}
  data:
    redis:
      host: ${REDIS_HOST:49.234.129.151}
      port: ${REDIS_DOCKER_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:49.234.129.151}
    port: ${RABBITMQ_LOCAL_PORT:25672}
    username: ${RABBITMQ_DEFAULT_USER:jin}
    password: ${RABBITMQ_DEFAULT_PASS:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
      static-locations: file:/data/res/
  mvc:
    static-path-pattern: /res/**

server:
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
