POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "username": "jun",
  "password":"123"
}

###

# @name login
GET http://localhost:8080/api/login?username=jun&password=123

@access_token = {{login.response.body.access_token}}
@refresh_token = {{login.response.body.refresh_token}}

###
# @name token_refresh
GET http://localhost:8080/api/user/token_refresh
AUTHORIZATION: Bearer {{refresh_token}}

@access_token = {{token_refresh.response.body.access_token}}
@refresh_token = {{token_refresh.response.body.refresh_token}}

###
# @name me
GET http://localhost:8080/api/user/me
AUTHORIZATION: Bearer {{access_token}}

###
# @name all
GET http://localhost:8080/api/user/all
AUTHORIZATION: Bearer {{access_token}}

###
# @name createRole
POST http://localhost:8080/api/user/createRole/后台
AUTHORIZATION: Bearer {{access_token}}
###
# @name deleteRole
POST http://localhost:8080/api/user/deleteRole/后台
AUTHORIZATION: Bearer {{access_token}}

###
# @name createRole
POST http://localhost:8080/api/user/createRole/前台
AUTHORIZATION: Bearer {{access_token}}

###
# @name deleteRole
POST http://localhost:8080/api/user/deleteRole/前台
AUTHORIZATION: Bearer {{access_token}}

###
# @name addRole
POST http://localhost:8080/api/user/addRole
AUTHORIZATION: Bearer {{access_token}}
Content-Type: application/json

{
    "username":"jun",
    "roleName": "财务"
}

###
# @name addRole
POST http://localhost:8080/api/user/addRole
AUTHORIZATION: Bearer {{access_token}}
Content-Type: application/json

{
    "username":"jun",
  "roleName": "前台"
}

###
# @name removeRole
POST http://localhost:8080/api/user/removeRole
AUTHORIZATION: Bearer {{access_token}}
Content-Type: application/json

{
    "username":"jun",
  "roleName": "前台"
}


###
GET http://localhost:8080/api/product
AUTHORIZATION: Bearer {{access_token}}

###
GET http://localhost:8080/api/product



